### ISSUE TITLE
windows store apps (phone 8.1 sdk)

### ISSUE THREAD

**Issue by Xianor** [strangeioc/strangeioc#153]
Hello. I am trying to build project for windows store (phone 8.1 sdk). 
And i have big problems with integration.
I have 43 +~ errors, that connected with reflection, like:

Assets\StrangeIoC\scripts\strange\extensions\command\impl\SignalCommandBinder.cs(129,52): error CS1061: 'System.Type' does not contain a definition for 'IsAssignableFrom' and no extension method 'IsAssignableFrom' accepting a first argument of type 'System.Type' could be found (are you missing a using directive or an assembly reference?

Assets\StrangeIoC\scripts\strange\extensions\dispatcher\eventdispatcher\impl\EventBinding.cs(110,34): error CS1061: 'System.Delegate' does not contain a definition for 'Method' and no extension method 'Method' accepting a first argument of type 'System.Delegate' could be found (are you missing a using directive or an assembly reference?)

Assets\StrangeIoC\scripts\strange\extensions\implicitBind\impl\ImplicitBinder.cs(49,24): error CS0117: 'System.Reflection.Assembly' does not contain a definition for 'GetExecutingAssembly'

Assets\StrangeIoC\scripts\strange\extensions\implicitBind\impl\ImplicitBinder.cs(78,31): error CS1929: Instance argument: cannot convert from 'System.Type' to 'System.Reflection.MemberInfo'

and others. Would you fix it and support this platform in future?

**Comment by WillzZz** [comment]
Unfortunately, Strange is not written with WinRT support in mind. Given Microsofts movement away from WinRT, I don't think that will change. RT is kind of a disaster. These methods do not exist in the WinRt / Metro codebase. They've basically taken .net, and sandboxed everything in to separate calls. It's annoying, to say the least. I have a good amount of experience working with RT here at Unity and it would require a large effort to rewrite strange to support it.

That having been said, it is almost surely doable, but I don't know the extent of the rewrite. Most of the methods referred to in .net/mono calls are available in some fashion in RT, you just have to hunt them down.  I would warmly welcome a fork of strangeioc for WinRT, but it's just not in the cards for Marc or I to have the time for it. Sorry!

**Comment by tomatell** [comment]
I have forked the StrangeIoC repo and refactored the code to work on Universal 8.1. However, I get the following error.

NullReferenceException: Object reference not set to an instance of an object.
   at strange.extensions.command.impl.SignalCommandBinder.Bind[T]()
   at CodenamePanda.Main.MainContext.mapBindings()
   at strange.extensions.context.impl.Context.Start()
   at strange.extensions.context.impl.Context..ctor(Object view, ContextStartupFlags flags)
   at strange.extensions.context.impl.Context..ctor(Object view)
   at strange.extensions.context.impl.CrossContext..ctor(Object view)
   at strange.extensions.context.impl.MVCSContext..ctor(MonoBehaviour view)
   at CodenamePanda.SignalContext..ctor(MonoBehaviour view)
   at CodenamePanda.Main.MainContext..ctor(MonoBehaviour view)
   at CodenamePanda.Main.MainRoot.Start()
   at CodenamePanda.Main.MainRoot.$Invoke1(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

I would appreciate it if you could look into the code and find out what is wrong.

The forked repo is here: https://github.com/tomatell/strangeioc

**Comment by unitymarc** [comment]
I'll take a gander at this tonight...but Will's more knowledgable on this topic, so it might need his input.

**Comment by tomatell** [comment]
OK.

**Comment by tomatell** [comment]
Any news?

**Comment by unitymarc** [comment]
Sorry, tomatell...wasn't able to get to it last night (got home kinda late). Will try to get some time over the weekend.

**Comment by PandaBinary** [comment]
OK. Thank you very much! I look forward to it.

Tom

**Comment by PandaBinary** [comment]
BTW. the link to StrangeIoC Github repo from your company's web page is 404 not found.
http://thirdmotion.github.io/strangeioc/

**Comment by unitymarc** [comment]
Thanks for the heads up. ThirdMotion was the original company behind Strange, but they're out of business now. I'm not sure who (if anyone) maintains that site. I'll get it changed if possible.

**Comment by tomatell** [comment]
Oh, I see.  That can explain.

**Comment by fogAndWhisky** [comment]
@tomatell I've looked this over, though I'm not at present set up to run Win8.1/Store, so I can't diagnose as fully as I'd like, and can't tell you *exactly* what's wrong. That said, the number of possible Null Pointers in SignalCommandBinder.Bind is exactly two, so this shouldn't be that hard to diagnose yourself.

**Possibility 1: The SignalCommandBinder doesn't have an InjectionBinder instance**
I'd start by checking that InjectionBinder is being instantiated at all (test that in your Context). Then I'd check to see if it's been properly injected into SignalCommandBinder (test in the Bind method). If InjectionBinder exists, move on to possibility 2.

**Possibility 2: The InjectionBinding returned on line 179 is null**
Break like 179 up like so:

    IInjectionBinding test = injectionBinder.Bind<T>();
    Debug.Log(test);
    test.ToSingleton();

If the Debug.Log is null, then that's your NPE.

Which is it? Not clear to me, though I'm inclined to place the blame on the first possibility, and specifically on a change to InjectionBinding in IsGenericTypeAssignable. That's just a guess. Hope that helps!

**Comment by tomatell** [comment]
Thanks for your followup. I have tested the possibility 2 with the sample project, StrangeRock, but there is no log generated. The log should be displayed in Visual Studio debug window, right?

**Comment by unitymarc** [comment]
As I say, I'm not really set up to test WinPhone stuff. I would presume, though, that a Google search would explain how to test and debug on such a device? Not really a VS user, so can't offer a lot of help there.

**Comment by WillzZz** [comment]
Did you figure this out? It's been over a year since I deployed a unity app to a windows 8.1 phone

**Comment by tomatell** [comment]
Will,

You don't mean you deployed StrangIoC to a windows 8.1 phone, do you?

**Comment by WillzZz** [comment]
No, I was testing unity ads with windows phone in preparation of WP 8.1 release.

**Comment by PandaBinary** [comment]
Windows Store Apps are inevitable for the further Windows development.

**Comment by PandaBinary** [comment]
Will,

Have you tried my code on the WSA 8.1 development environment?

I have debugged as fogAndWhisky described in the possiblity 2.
I got these errors when binding StartSignal to the main start command.

Debugging.........................
Exception thrown: 'System.NullReferenceException' in Assembly-CSharp.DLL
'Template.exe' (Win32): Loaded 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll'. Symbols loaded.
Exception.........................System.NullReferenceException: Object reference not set to an instance of an object.
   at strange.extensions.command.impl.SignalCommandBinder.Bind[T]()
Exception thrown: 'System.NullReferenceException' in Assembly-CSharp.DLL
Exception: Object reference not set to an instance of an object.
Type: System.NullReferenceException
Module: Assembly-CSharp
InnerException: <No Data>
AdditionalInfo:<No Data>
   at strange.extensions.command.impl.SignalCommandBinder.Bind[T]()
   at CodenamePanda.Main.MainContext.mapBindings()
   at strange.extensions.context.impl.Context.Start()
   at strange.extensions.context.impl.Context..ctor(Object view, ContextStartupFlags flags)
   at CodenamePanda.Main.MainRoot.$Invoke1(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method)
 
(Filename:  Line: 0)

**Comment by WillzZz** [comment]
Not yet, I've been busy testing and merging branches to tip. I just found a windows phone lying around the office so maybe I'll give it a shot later this week.

**Comment by tomatell** [comment]
OK. Thanks.

**Comment by PandaBinary** [comment]
Hi Will,

Have you had any chance to try out the code? Actually, it doesn't have to be a Windows Phone. 
You could try with Windows Store Apps 8.1.

**Comment by WillzZz** [comment]
Just poked around with it, Visual Studio is being awful so I can't build properly. I'll try it at home since I need to update my vs2013 work license.

More importantly, we've been talking with Microsoft a lot this week and UWP is like two weeks away. I don't know what your use case is, but their advice is to ignore 8.1 stuff if possible and just wait for UWP. Xbox one won't support UWP in their store at first (fall?), but of course unity has its own xbone build path, anyways. 

So official microsoft word is get away from that metro/8.1 stuff and move to their newest latest great with UWP / w10.

If you're targeting phones it is possible you are stuck with 8.1 for the time being :( That's more of a carrier thing, than a Microsoft thing, though.

**Comment by PandaBinary** [comment]
Hi Will,

Thanks for trying.  I was able to successfully compile it. However, it ends up as an error when I run the app. Well, the issue lies on Reflection API.  As you may already know, access to some .NET Framework types and members is restricted in WSA 8.1.  I assume this would be the same in UWP / W10.
Therefore, we will further continue to resolve this issue on WSA 8.1. I would assume that, if we resolved this issue, it should be easy to migrate it to  UWP / W10 as well.

**Comment by WillzZz** [comment]
I like to think UWP will be infinitely better. WinRT was a disaster. They've at least internally admitted that much. Breaking every API is an awful plan, so I think they'll revert loads of it.

As for reflection, yes it has all been changed. Rewriting strange for WinRT will be a significant undertaking. We have an internal tool I wanted to try which will patch a dll from .net 3 to winrt compatibility but I haven't gotten the chance to try it. Send me an email at my work email willc@unity3d.com I'll get you hooked up with someone.

**Comment by PandaBinary** [comment]
I have rewrote strange yet none has tried to test it. There won't be any error when you build it on VS.
BTW, I have not yet received any reply through email.

**Comment by PandaBinary** [comment]
It looks like there is a problem on constructors.

[15.415088 / 128.966917] - First level loaded
[15.618495 / 128.967374] - AppCallbacks::Load
[0.000805 / 128.967722] - PerformUpdateAndRender started
constructors: Void .ctor()
InjectMember: Inject[]

**Comment by PandaBinary** [comment]
private ConstructorInfo findPreferredConstructor(Type type) has the problem.

#if NETFX_CORE
            IEnumerable<ConstructorInfo> constructorsquery = type.GetTypeInfo().DeclaredConstructors.Where(m => m.IsPublic);
            ConstructorInfo[] constructors = constructorsquery.Cast<ConstructorInfo>().ToArray();


#else
            ConstructorInfo[] constructors = type.GetConstructors(BindingFlags.FlattenHierarchy |
                                                                        BindingFlags.Public |
                                                                        BindingFlags.Instance |
                                                                        BindingFlags.InvokeMethod);

#endif
			if (constructors.Length == 1)
			{
                System.Diagnostics.Debug.WriteLine("constructors: " + constructors[0].ToString());
                return constructors [0];
			}

**Comment by PandaBinary** [comment]
It looks like the Unity3d project cannot be opened with Visual Studio 2015 after updating the latest Windows Update, KB3083185, which installs .NET 4.6 framework.  Does anybody experience this?

**Comment by pratscgstudio** [comment]
Any updates on Universal Windows Apps Support? With the release of W10 it should prove to be quiet useful. I just learnt about StrangeIoC today. Still learning how to use to use it correctly. I would be more than happy to help you guys test stuff out if you need to.

**Comment by PandaBinary** [comment]
The Reflection API is the blocker.  You may have to create Type Extensions for that to work. I'm working on it, but not yet verified to work.
